<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Onestepcheckout
 * @author     Suporte <suporte@inovarti.com.br>
 */
?><?php if ($this->getTotals()): ?>
    <tfoot>
    <?php $_colspan = (Mage::helper('onestepcheckout/config')->getIsCartEditable()?4:3); ?>
    <?php echo $this->renderTotals(null, $_colspan); ?>
    <?php echo $this->renderTotals('footer', $_colspan); ?>
    <?php if ($this->needDisplayBaseGrandtotal()):?>
        <tr>
            <td class="a-right" colspan="<?php echo $_colspan; ?>">
                <small><?php echo $this->helper('sales')->__('Your credit card will be charged for') ?></small>
            </td>
            <td class="a-right">
                <small><?php echo $this->displayBaseGrandtotal() ?></small>
            </td>
        </tr>
    <?php endif?>
    </tfoot>
<?php endif; ?>

<script type="text/javascript">
$j = jQuery.noConflict();
        $j(document).ready(function(){
        if($j('#p_method_pagseguro_cc').is(':checked')){
        if(typeof PagSeguroDirectPayment != "undefined" && PagSeguroDirectPayment.ready){
        RMPagSeguro.getInstallments();
        }
     }
});


</script>

